<?php 
use Core\Router;
$app = new Router($dbc);

$app::get('/','HomeController','view');
$app::get('/contact-us','ContactController','index');
$app::post('/contact-us','ContactController','save');
$app::get('/contact-us/delete','ContactController','delete');
$app::get('/login','AuthController','index');
$app::get('/logout','AuthController','logout');
$app::post('/login','AuthController','authentication');
$app::get('/admin','IndexController','index');
$app::get('/user-profile','UserProfileController','index');
$app::post('/user-profile','UserProfileController','update');
$app::get('/change-password','ChangePasswordController','index');
$app::get('/signup','SignUpController','index');
$app::post('/signup','SignUpController','save');
$app::get('/users','UserController','index');
$app::post('/users/update','UserController','update');
$app::post('/users','UserController','save');
$app::post('/users/delete','UserController','delete');
$app::get('/rooms','RoomController','index');
$app::post('/rooms','RoomController','save');
$app::post('/rooms/update-image','RoomController','updateImage');
$app::post('/rooms/update','RoomController','update');
$app::post('/rooms/delete','RoomController','delete');
$app::get('/featureimages','FeatureImageController','index');
$app::post('/featureimages','FeatureImageController','save');
$app::post('/featureimages/update','FeatureImageController','update');
$app::post('/featureimages/delete','FeatureImageController','delete');
$app::get('/room-list','RoomShowController','index'); 
$app::post('/room-list','RoomShowController','search');
$app->run();